-- API 명세서 v1.1 3-9 (DB 테이블 매핑) 기준
-- 프로젝트 · 스터디의 status는 컬럼으로 두지 않는다 (period_end로 조회 시 계산)
-- 자식 테이블의 (parent_id, sort_order)에는 UNIQUE를 걸지 않는다:
--   PUT 전체 교체(clear + addAll) 시 Hibernate가 INSERT를 DELETE보다 먼저 실행하기 때문

-- ─────────────────────────── project ───────────────────────────
CREATE TABLE project (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          varchar(60)  NOT NULL,
    title         varchar(40)  NOT NULL,
    summary       varchar(80)  NOT NULL,
    category      varchar(30)  NOT NULL,
    period_start  date         NOT NULL,
    period_end    date,
    thumbnail_url varchar(500),
    github_url    varchar(500),
    demo_url      varchar(500),
    description   jsonb        NOT NULL DEFAULT '[]',
    tech_stack    jsonb        NOT NULL DEFAULT '[]',
    features      jsonb        NOT NULL DEFAULT '[]',
    outcomes      jsonb        NOT NULL DEFAULT '[]',
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_project_slug UNIQUE (slug),
    CONSTRAINT ck_project_category CHECK (category IN ('solution-challenge', 'team-project', 'official')),
    CONSTRAINT ck_project_period_start_first_day CHECK (EXTRACT(DAY FROM period_start) = 1),
    CONSTRAINT ck_project_period_end_first_day CHECK (period_end IS NULL OR EXTRACT(DAY FROM period_end) = 1),
    CONSTRAINT ck_project_period CHECK (period_end IS NULL OR period_end >= period_start)
);

CREATE TABLE project_team (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint      NOT NULL,
    name       varchar(20) NOT NULL,
    role       varchar(20) NOT NULL,
    sort_order int         NOT NULL,
    CONSTRAINT fk_project_team_project FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE
);

-- ─────────────────────────── study ───────────────────────────
CREATE TABLE study (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         varchar(60) NOT NULL,
    title        varchar(40) NOT NULL,
    summary      varchar(80) NOT NULL,
    topic        varchar(20) NOT NULL,
    period_start date        NOT NULL,
    period_end   date,
    leader       varchar(20) NOT NULL,
    format       varchar(30),
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_study_slug UNIQUE (slug),
    CONSTRAINT ck_study_period_start_first_day CHECK (EXTRACT(DAY FROM period_start) = 1),
    CONSTRAINT ck_study_period_end_first_day CHECK (period_end IS NULL OR EXTRACT(DAY FROM period_end) = 1),
    CONSTRAINT ck_study_period CHECK (period_end IS NULL OR period_end >= period_start)
);

CREATE TABLE study_participant (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id   bigint      NOT NULL,
    name       varchar(20) NOT NULL,
    sort_order int         NOT NULL,
    CONSTRAINT fk_study_participant_study FOREIGN KEY (study_id) REFERENCES study (id) ON DELETE CASCADE
);

CREATE TABLE study_output (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id   bigint       NOT NULL,
    label      varchar(30)  NOT NULL,
    url        varchar(500) NOT NULL,
    sort_order int          NOT NULL,
    CONSTRAINT fk_study_output_study FOREIGN KEY (study_id) REFERENCES study (id) ON DELETE CASCADE
);

-- ─────────────────────────── event ───────────────────────────
CREATE TABLE event (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      varchar(40) NOT NULL,
    category   varchar(20) NOT NULL,
    start_date date        NOT NULL,
    end_date   date,
    time_text  varchar(20),
    place      varchar(40),
    summary    varchar(80),
    sort_order int         NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_event_category CHECK (category IN
        ('meeting', 'seminar', 'project', 'study', 'festival', 'presentation', 'milestone')),
    CONSTRAINT ck_event_period CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_event_sort_order CHECK (sort_order >= 0)
);

-- ─────────────────────────── member ───────────────────────────
CREATE TABLE member (
    id                   bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status               varchar(10)  NOT NULL,
    role                 varchar(20),
    name                 varchar(20)  NOT NULL,
    photo_url            varchar(500),
    department           varchar(30)  NOT NULL,
    history              jsonb        NOT NULL DEFAULT '[]',
    interests            jsonb        NOT NULL DEFAULT '[]',
    part                 varchar(20)  NOT NULL,
    bio                  varchar(60)  NOT NULL,
    github_url           varchar(500),
    homepage_url         varchar(500),
    consent_confirmed_at timestamptz  NOT NULL,
    created_at           timestamptz  NOT NULL DEFAULT now(),
    updated_at           timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_member_status CHECK (status IN ('core', 'senior')),
    CONSTRAINT ck_member_role CHECK (role IS NULL OR role IN ('lead', 'part-lead', 'core')),
    -- 코어멤버는 role 필수, 시니어는 role 금지
    CONSTRAINT ck_member_status_role CHECK (
        (status = 'core' AND role IS NOT NULL) OR (status = 'senior' AND role IS NULL)
    ),
    CONSTRAINT ck_member_part CHECK (part IN ('frontend', 'backend', 'mobile', 'ai-ml', 'design'))
);

-- ─────────────────────────── site_setting / site_stat ───────────────────────────
CREATE TABLE site_setting (
    id            smallint     PRIMARY KEY,
    recruiting    boolean      NOT NULL,
    banner_text   varchar(60)  NOT NULL,
    recruit_start date,
    recruit_end   date,
    updated_at    timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_site_setting_single_row CHECK (id = 1),
    CONSTRAINT ck_site_setting_recruit_period CHECK (
        (recruit_start IS NULL AND recruit_end IS NULL)
        OR (recruit_start IS NOT NULL AND recruit_end IS NOT NULL AND recruit_start <= recruit_end)
    )
);

CREATE TABLE site_stat (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_id smallint    NOT NULL,
    sort_order int         NOT NULL,
    label      varchar(20) NOT NULL,
    value      int         NOT NULL,
    unit       varchar(10),
    suffix     varchar(5),
    CONSTRAINT fk_site_stat_setting FOREIGN KEY (setting_id) REFERENCES site_setting (id),
    CONSTRAINT uk_site_stat_sort_order UNIQUE (sort_order),
    CONSTRAINT ck_site_stat_sort_order CHECK (sort_order BETWEEN 1 AND 4),
    CONSTRAINT ck_site_stat_value CHECK (value >= 0)
);

-- ─────────────────────────── admin_user ───────────────────────────
CREATE TABLE admin_user (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id      varchar(40)  NOT NULL,
    password_hash varchar(100) NOT NULL,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_admin_user_login_id UNIQUE (login_id)
);
